blueprint:
  name: Update Entity Offset
  description: Update the offset attribute of an entity based on another sensor's state
  domain: automation
  input:
    sensor_to_monitor:
      name: Zigbee Sensor to Monitor
      selector:
        entity:
          domain: sensor
    entity_to_update:
      name: Tado Entity to Update
      selector:
        entity:
          domain: climate

trigger:
  - platform: time_pattern
    minutes: /15

action:
  - service: tado.set_climate_temperature_offset
    data:
      offset: "{{ states(sensor_to_monitor) | float(0) - state_attr(entity_to_update, 'current_temperature') | float(0) }}"
    target:
      entity_id: !input entity_to_update
